version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  labels:
  - "Dependency: Gems"
  ignore:
  - dependency-name: bootstrap
    versions:
    - "< 4.1, > 4.0.0"
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: bullet
    versions:
    - 6.1.3
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: webpacker
    versions:
    - 5.2.1
