# https://raw.githubusercontent.com/thoughtbot/hound/master/config/style_guides/ruby.yml

Layout/AlignArray:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
LineLength:
  Max: 80
ExtraSpacing:
  Enabled: false
AbcSize:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
AmbiguousOperator:
  Enabled: false
MultilineMethodCallIndentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
